const BOOKING_STATUS = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  SKIPPED: "SKIPPED",
  EXPIRED: "EXPIRED"
};

const MEAL_TYPES = ["BREAKFAST", "LUNCH", "DINNER"];

module.exports = { BOOKING_STATUS, MEAL_TYPES };
